/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_JniDemo */

#ifndef _Included_com_JniDemo
#define _Included_com_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
	/*
	* Class:     com_JniDemo
	* Method:    set
	* Signature: (I)V
	*/
	JNIEXPORT void JNICALL Java_com_JniDemo_set
	(JNIEnv *, jclass, jint);

	/*
	* Class:     com_JniDemo
	* Method:    get
	* Signature: ()I
	*/
	JNIEXPORT jint JNICALL Java_com_JniDemo_get
	(JNIEnv *, jclass);

	/*
	* Class:     com_JniDemo
	* Method:    RemoveUnline
	* Signature: (Ljava/lang/String;Ljava/lang/String;IIII)V
	*/
	JNIEXPORT void JNICALL Java_com_JniDemo_RemoveUnline
	(JNIEnv *, jclass, jstring, jstring, jint, jint, jint, jint);

	/*
	* Class:     com_JniDemo
	* Method:    ImageRecify
	* Signature: (Ljava/lang/String;Ljava/lang/String;)D
	*/
	JNIEXPORT jdouble JNICALL Java_com_JniDemo_ImageRecify
	(JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
