/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_IdentityCard */

#ifndef _Included_com_IdentityCard
#define _Included_com_IdentityCard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_IdentityCard
 * Method:    IdentityCardTrans
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_IdentityCard_IdentityCardTrans
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
