/* DO NOT EDIT THIS FILE - it is machine generated */
#include"jni.h"
/* Header for class com_RemoveBlackBorderDll */

#ifndef _Included_com_RemoveBlackBorderDll
#define _Included_com_RemoveBlackBorderDll
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_RemoveBlackBorderDll
 * Method:    RemoveBlackBorder
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_RemoveBlackBorderDll_RemoveBlackBorder
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
