/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_BlankPageDetectDLL */

#ifndef _Included_com_AllInOneEnhance
#define _Included_com_AllInOneEnhance
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_BlankPageDetectDLL
 * Method:    BlankPageDetect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jdouble JNICALL Java_com_AllInOneEnhance_enhance
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
