/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_BlankPageDetectDLL */

#ifndef _Included_com_BlankPageDetectDLL
#define _Included_com_BlankPageDetectDLL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_BlankPageDetectDLL
 * Method:    BlankPageDetect
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_BlankPageDetectDLL_BlankPageDetect
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
